---
title: "case_study"
author: "Bohan Zhu"
date: "2025-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

data(nyc_airbnb)
```

```{r}
str(nyc_airbnb)
```

Let's look at prices first
```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(room_type, neighbourhood_group) |> 
  summarize(
    mean_price = mean(price),
    mi_price = min(price),
    max_price = max(price)
  ) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```


```{r}
nyc_airbnb |> 
  count(neighbourhood_group, room_type)
```


Make some plots

```{r}
nyc_airbnb |> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(room_type ~ neighbourhood_group)
  scale_x_continuous(limits = c(0, 1000))
```



```{r}
nyc_airbnb |> 
  filter(neighbourhood_group == "Manhattan",
           price <500,
         room_type == "Entire home/apt"
         ) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_violin() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

remember to look at extreme values

```{r}
nyc_airbnb |> 
  filter(price > 9000)
```



```{r}
nyc_airbnb |> 
  filter(calculated_host_listings_count > 30)
```


Keep looking at location

```{r}
nyc_airbnb |> 
  filter(neighbourhood_group == "Manhattan",
           price <1000,
         room_type == "Entire home/apt"
         ) |> 
  ggplot(aes(x = lat, y = long, color = review_scores_location)) +
  geom_point()
```

can we make a better map

```{r}

pal <- colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$review_scores_location
)


nyc_airbnb |> 
  filter(neighbourhood_group == "Manhattan",
           price <1000,
         room_type == "Entire home/apt"
         ) |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~lat, ~long, 
                   color = ~pal(review_scores_location),
                   radius = 2)
```


